/**
 * Generated regions inside otherwise hand-maintained files.
 *
 * The template needs a few facts to appear in files that people also edit — the repository map in
 * CLAUDE.md, the project context OpenSpec shows the agent. Regenerating a whole file would destroy
 * the surrounding prose; leaving the facts to be copied by hand guarantees they go stale. So each
 * such file carries one delimited region that `sync` owns, and `check` fails when a region no
 * longer matches its source.
 *
 * The boundary matters in the other direction too: `openspec update` regenerates
 * `.claude/commands/opsx/**` and `.claude/skills/openspec-*`. Verified against the pinned CLI:
 * it does not touch `openspec/config.yaml`, so a region placed there survives an OpenSpec upgrade.
 */

import fs from 'node:fs';
import path from 'node:path';

export class RegionError extends Error {
  constructor(message) {
    super(message);
    this.name = 'RegionError';
  }
}

/**
 * Replace the content between the markers, keeping everything outside them untouched.
 * Both markers must be present exactly once, or the file is left alone and an error is raised —
 * guessing where a region was meant to go is how a generator eats someone's work.
 */
export function replaceRegion(text, begin, end, body) {
  const beginIndex = text.indexOf(begin);
  const endIndex = text.indexOf(end);

  if (beginIndex === -1 || endIndex === -1) {
    throw new RegionError(
      `Could not find the generated region markers.\n  begin: ${begin}\n  end:   ${end}`
    );
  }
  if (text.indexOf(begin, beginIndex + begin.length) !== -1) {
    throw new RegionError(`The begin marker appears more than once: ${begin}`);
  }
  if (text.indexOf(end, endIndex + end.length) !== -1) {
    throw new RegionError(`The end marker appears more than once: ${end}`);
  }
  if (endIndex < beginIndex) {
    throw new RegionError('The end marker appears before the begin marker.');
  }

  const before = text.slice(0, beginIndex + begin.length);
  const after = text.slice(endIndex);

  return `${before}\n${body}\n${after}`;
}

/** Current content of a region, for drift detection. */
export function readRegion(text, begin, end) {
  const beginIndex = text.indexOf(begin);
  const endIndex = text.indexOf(end);
  if (beginIndex === -1 || endIndex === -1 || endIndex < beginIndex) {
    throw new RegionError(
      `Could not find the generated region markers.\n  begin: ${begin}\n  end:   ${end}`
    );
  }
  return text.slice(beginIndex + begin.length, endIndex);
}

/** Indent every non-empty line, for embedding a block inside a YAML scalar. */
function indent(text, prefix) {
  return text
    .split('\n')
    .map((line) => (line.trim().length === 0 ? '' : prefix + line))
    .join('\n');
}

/**
 * The repository map rendered into CLAUDE.md. Derived entirely from the configuration, so the
 * agent's context cannot disagree with the repository's actual layout.
 */
export function renderClaudeRegion(config) {
  const modules =
    config.architecture.modules.length === 0
      ? 'none registered'
      : config.architecture.modules.map((m) => `${m.name} (contract: ${m.contract})`).join(', ');

  const integrations = [
    `database: ${config.integrations.database}`,
    `deployment: ${config.integrations.deployment}`,
    `mcp: ${config.integrations.mcp.enabled ? 'enabled' : 'disabled'}`,
  ].join(', ');

  return [
    '<!-- Generated by `node tools/repo.mjs sync` from project.config.json. Do not edit by hand. -->',
    '',
    `- Solution: \`${config.paths.solutionFile}\` (root namespace \`${config.rootNamespace}\`)`,
    `- Production projects: \`${config.paths.src}/${config.solutionName}.{Domain,Application,Infrastructure,Api}\``,
    `- Test projects: \`${config.paths.tests}/${config.solutionName}.{UnitTests,ArchitectureTests,IntegrationTests}\``,
    `- Negative architecture fixtures: \`${config.paths.tests}/fixtures/\``,
    `- Architecture profile: \`${config.architecture.profile}\` — modules: ${modules}`,
    `- Optional integrations: ${integrations}`,
    `- Documentation language: \`${config.documentation.language}\``,
    `- Archive gate: ${config.openspec.archiveGate.enabled ? `enabled, scope \`${config.openspec.archiveGate.scope}\`` : 'disabled'}`,
  ].join('\n');
}

/**
 * The project context rendered into openspec/config.yaml. Its body is the team-maintained
 * `openspec/project-context.md` with the heading and the instructions to the maintainer stripped,
 * plus the configuration facts the agent needs while writing artifacts.
 */
export function renderOpenSpecRegion(config, projectContextMarkdown) {
  const body = stripAuthoringPreamble(projectContextMarkdown);

  const header = [
    'Generated by `node tools/repo.mjs sync` from openspec/project-context.md.',
    'Edit that file, not this region.',
    '',
    `Solution: ${config.solutionName} (root namespace ${config.rootNamespace})`,
    `Architecture profile: ${config.architecture.profile}`,
    `Language for artifacts: ${config.documentation.language}`,
  ].join('\n');

  // One blank line between the header and the first section, so the rendered block reads as prose
  // rather than running the heading onto the last header line.
  return indent(`${header}\n\n${body.trimStart()}`.trimEnd(), '  ');
}

/**
 * Drop the top heading and the paragraphs addressed to whoever maintains the file: they explain
 * how to edit it, which is noise in an agent's planning context.
 */
function stripAuthoringPreamble(markdown) {
  const lines = markdown.split('\n');
  const firstSection = lines.findIndex((l) => l.startsWith('## '));
  return firstSection === -1 ? markdown : lines.slice(firstSection).join('\n');
}

/**
 * Compute what each generated region should contain.
 *
 * @returns {Array<{file: string, begin: string, end: string, body: string, source: string}>}
 */
export function plannedRegions(root, config, manifest) {
  const projectContextPath = path.join(root, 'openspec', 'project-context.md');

  return manifest.generatedRegions.map((region) => {
    let body;
    if (region.file === 'CLAUDE.md') {
      body = renderClaudeRegion(config);
    } else if (region.file === 'openspec/config.yaml') {
      if (!fs.existsSync(projectContextPath)) {
        throw new RegionError(
          `openspec/config.yaml declares a generated region sourced from ` +
            `openspec/project-context.md, which does not exist.`
        );
      }
      body = renderOpenSpecRegion(config, fs.readFileSync(projectContextPath, 'utf8'));
    } else {
      throw new RegionError(
        `tools/rename.manifest.json declares a generated region for "${region.file}", ` +
          'but tools/lib/generated.mjs has no renderer for it.'
      );
    }

    return { ...region, body };
  });
}

/**
 * Apply the planned regions.
 *
 * @param {boolean} dryRun When true, nothing is written.
 * @returns {Array<{file: string, changed: boolean, missing: boolean}>}
 */
export function applyRegions(root, planned, dryRun) {
  return planned.map((region) => {
    const file = path.join(root, region.file);

    if (!fs.existsSync(file)) {
      return { file: region.file, changed: false, missing: true };
    }

    const current = fs.readFileSync(file, 'utf8');
    const updated = replaceRegion(current, region.begin, region.end, region.body);

    if (updated === current) {
      return { file: region.file, changed: false, missing: false };
    }

    if (!dryRun) {
      fs.writeFileSync(file, updated, 'utf8');
    }

    return { file: region.file, changed: true, missing: false };
  });
}

/**
 * Regions whose content no longer matches what `sync` would write.
 *
 * @returns {Array<{file: string, reason: string}>}
 */
export function findDrift(root, planned) {
  const drift = [];

  for (const region of planned) {
    const file = path.join(root, region.file);

    if (!fs.existsSync(file)) {
      drift.push({ file: region.file, reason: 'the file does not exist' });
      continue;
    }

    const current = fs.readFileSync(file, 'utf8');

    let actual;
    try {
      actual = readRegion(current, region.begin, region.end);
    } catch (error) {
      drift.push({ file: region.file, reason: error.message });
      continue;
    }

    if (actual.trim() !== region.body.trim()) {
      drift.push({
        file: region.file,
        reason: `the generated region does not match its source (${region.source}). ` +
          'Run `node tools/repo.mjs sync`.',
      });
    }
  }

  return drift;
}
