// <auto-generated />
using EscapeNow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EscapeNow.Infrastructure.Persistence.Migrations;

[DbContext(typeof(CityCatalogDbContext))]
[Migration("20260908190000_InitialCities")]
partial class InitialCities
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        CityCatalogModel.Build(modelBuilder);
#pragma warning restore 612, 618
    }
}
