// <auto-generated />
using EscapeNow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EscapeNow.Infrastructure.Persistence.Migrations;

[DbContext(typeof(CityCatalogDbContext))]
partial class CityCatalogDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        CityCatalogModel.Build(modelBuilder);
#pragma warning restore 612, 618
    }
}

internal static class CityCatalogModel
{
    internal static void Build(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
        NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");

        modelBuilder.Entity("EscapeNow.Infrastructure.Persistence.CityRecord", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedNever()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("Country")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("country");

            b.Property<string>("ImageUrl")
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnType("character varying(2000)")
                .HasColumnName("image_url");

            b.Property<double>("Latitude")
                .HasColumnType("double precision")
                .HasColumnName("latitude");

            b.Property<double>("Longitude")
                .HasColumnType("double precision")
                .HasColumnName("longitude");

            b.Property<string>("Name")
                .IsRequired()
                .HasColumnType("citext")
                .HasColumnName("name");

            b.HasKey("Id")
                .HasName("pk_cities");

            b.HasIndex("Name")
                .IsUnique()
                .HasDatabaseName("ix_cities_name");

            b.ToTable("cities", (string)null);
        });
    }
}
