<Project Sdk="Microsoft.NET.Sdk">

  <!-- Infrastructure implements the ports declared by Application. -->

  <ItemGroup>
    <ProjectReference Include="../EscapeNow.Application/EscapeNow.Application.csproj" />
    <ProjectReference Include="../EscapeNow.Domain/EscapeNow.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
